apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }} 
data:
  foo: bar
  my-var: value
  other-var: other-value
  properties-file: |
    {{- range .Values.properties }}
    {{ . | upper | quote }}
    {{- end }}
  message.txt: |
   <h1> Hello from configmap </h1>

  LOG_LEVEL: INFO
  
