apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: java-api-build
spec:
  params:
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-name
    value: $(body.repository.name)
  - name: git-branch
    value: $(body.head_commit.id)
